apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Sfxx6Yt2NsWHRQoNW+WAZZ3RyolCokzl+qKVcaaKcj9B2s5YSI06Lw4YBtry8S3rypfVJ7YXcc8WywAeueDtHdqL8RN/rYEYDAcnZE9p4RLiLpyj5cydT0g3U3DT+KhC9ZKpVAbnJQE2bkcOCvYS1GQOIgsBqAFEKib+oDc/7n2O7Vg65ndU9NZ6BkOVvRhw/u9QxuRP20zK2V58+AywrrmTb63zFlfSsvv9Sx8VAQoRyJH4BAryHrWMCwdZSx/5jyCXKXRcNqFF3PL46RWgj5onTxNMw4Gt7Sadc/dE8BtwSUIOhGDOzEpyV1c=,iv:3EIT+Kq8MgnOyW9FCpuVIsMIFXPPTI1H0kpfJTfimBc=,tag:7bNmsh0/kcBFiLqe9HQIcQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WXFGUGlITkxlWVB0ZzR2
            cEdCTklkZUJMbnlkc3NXKzl5WVlDaG8weUVjClFOQ0RsNy9LRHh3ZGRqOERNT2ZY
            c0p4enFLVVI2ZE0zZlZlSVI2ZHhEVVUKLS0tIGFtM055alhWanpPMlJaYXptd3Nn
            MzVHSHNxNTlxSGhKRUZ2RmNEMTUyT2MKlzz9zH+wLQAsxw4YApg8weEiKcvtdZYO
            DnQSYNspHQ+12f8Nk82/qIZQh1AEnmnSe2JBz0m6SwNSVcLpJ3mi6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T04:41:13Z"
    mac: ENC[AES256_GCM,data:ReuJT8BfpjRpkLNV2AhwQWLiFGMqxyOkrNrXqdiOstj3zoTWHi8KASk439BINsaWNvUJWEGzJASA4hTPfqDevq6XKCNlBJI5+LwHeAM0I0ZtsCuzB9bmjWGVgixt7hp2jACQtzxIaZFgsV8I/HlOSj4GgUBEAKERuy2u9EE114c=,iv:JaJFlLJCIkAnqVb80azIsIPGyiHn0tfmhLIj5SOV7TY=,tag:vJKDMu3YmN/uddbG5EWdnA==,type:str]
    version: 3.13.3
