apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cGG2IgumnC+zuyvptaRNNpRo478KyKakwlXjrQLOpYFpVroPEWLQCGsmcAZw8D/OF0X6oE95WnFxF9gL4Zf57H0u/hdMIIxwsYB9+POzCSvmCB/XkpoSLgUyGSWSY/9qvS8d4nO8RBgZAIrFoNJeHY732mXFDhpyM/ShPK6+2hlxhYyJsgOvxVPAAffPa25P0M3Eax082DyqSjJUqwGAZkBaW+kxWJrHSvgSobQZvFELqwlNU0CJ4X6LPVcXBwPwHjq301wRdaRL/r5jUb9B/5ZeSKsDK8JJ89U5Kb/erhpsze3n9lz5EjkTurI=,iv:Mnjc9SqpyF3AhLeSsOp+3I/HudovxOfeLO+i9zaSn9M=,tag:jx0T9Xo857oyQB0n0bqF9A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3VPKy8vTGFiKzZPQndj
            YzlPUE5mL0xDSTNtcS9HdnFsNXZ0SmlLelRFClpXYkZIR0MyaGtIWDRjOUZzbHdv
            M1JJOVhrV2xWWDRnU3dtNXJ2ZWlNYTAKLS0tIHVHMU1YbW1pZGk5N0s2VEVoU2w1
            R3BHV2JTMkZxQ0lPbEo3TEZBUSsyancKS7ALogstEhaDVbnOJJ4Inbdu5vyt9jsw
            x8PaAqpfUEBxGkukoXgyyiAhY4/OwhPYXfi+scg71P7iige+UfFrEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12plyrrm69vs9n5rjzlzqc6y33qrtgvpy0f5l847vswpqjaztzcgq22w8jq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T05:57:34Z"
    mac: ENC[AES256_GCM,data:f3Tf0DLva4gQd2eYNJItKFZri1CxCkcNeXACIUwnEygk98ekIVTluat/+RZOOZeKV0tZEeiaaR5Gps/sINEH2Sk1G9sVFxuGm4SeFHyjPHraiMbwLeMSzYatuafB76M1xzehpB+kDxdk4+qCQRX0CFNZrYTWpUNf18KbiDr3c4w=,iv:NP+UMYhlUiskaTaY3m9UONhGfkEe5vcFHM/FMMIt+6Q=,tag:Z62AmnXz1gC6zyiNhdYeJA==,type:str]
    version: 3.13.3
