apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cRvrOLF/4ISK8LVhQNM6uRdWtVvTvv3JAcZAgef7QL0Q5no/Rzws43o0RG2cKmUQxZWRTumPiFV3lPnH+9ryoWLO7Ew2ESWLuHqmZTjU1DUUGO8KOhS2nU+Gs1sH1vUxm3sm4MM6+5WOlCDEcc1mhudBMcvWg1NMSk86eW2XrZ+qoXT0dUQLqenkKOueRsr896yOdQ9wtTGC6+GHEKmyHyk1ppAyikmGZ8ao8TcUbfcWNNZHBdy+AQTh6yBBN0fvRxpl6bwLaZxwewSAFlrvl2O+f1ndOLjp0SSXghjsq5sO9HqO0UHVju+8YnE=,iv:a+yA2XDwvgT3Zhg0V/LlhUi5h6HOqJpTjTWJ8CiGnic=,tag:1TiEFehcvFFgW21UI3Fnhw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVmVXdllrQ3NaZUhLS0do
            UzlaNVNxUVppOGtaQk9STGVoREJ1THYxUEY0ClgyT25Rc3ZySlVQQ1lkdnBlSXZo
            QzhiV25LeFB2N2R2N2FiOHkzSFdiRHcKLS0tIGRPWWRUVnFnS1FZemJ1dHB1eVVz
            L1duUFF5UE9hcTlucHFwMUVxV08yZXMKtFqj1MWC65tO4sLWg/Joeb2WUzH9YlbI
            6BTabgXr07ZcylbyxBLuSGt+bLa+/VF8snP8GDoBExaY2JEGdM735A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T04:52:01Z"
    mac: ENC[AES256_GCM,data:b53oP6Ide3LSam/4bOPo3McUewaV1MLnY8hTmKdf/ZxV+GHo3ycUxi21FuquplZHo5jSW6PpuuCctDmizTZi6KF978WM/t3mcG+BEDj6I9fq5GATLRBbskdXqSTQujXZMZqHfTceomt+jtVRj8AMEEAu0+TTl9UCV7IUk80pAwQ=,iv:MWcCxuufcxZV1QXEppJaq+zV3Ek/MwMriNV91c0dOG0=,tag:42ZC8hfv96wQqv+vG2mkPA==,type:str]
    version: 3.13.3
