apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:b4/bDyflM/j/WCwG,iv:QXXzsoQT5EmDlvRbKbcFRiN1iVB0m5OZhAMYoXZnlvM=,tag:NpmpceTjp3uVt/lkbaBGow==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ORkuYvaQSUU/qzS9,iv:9hpW1mqWB8j88QUyXkyQ7mn9LUheI3lmXGt2Ur/Oxsk=,tag:j3+AsdOOwmDz1FokQfB+rQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLblJaNElsbjBOc0hTbGd2
            L1YzNm5ReXkzaXBQSFlqa2hUTWJKbzVvQkRrClFPbXRhS1dOQlp6cEg5VDNXeVgy
            OVhIMWU5ajZCcDduT2s4eU0zb2ZzTVkKLS0tIHEyZmlhQ2VaNGUydjlRaWc2ZWFC
            WXZ2dGZZSm44emt4eHlXR1phazZMREUKrRXj19yLNVcGj0lWKGdX6uz9ZYkw0K53
            i/Ffxdwj64xM9ky9CokkbDVp2tuubEiaRol6k/XFAE9miDMmcP8K0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T04:55:37Z"
    mac: ENC[AES256_GCM,data:GUqcQaU2sOg9Lj/sFzLG/D17lS4p44PxFeiOtZJODBvMLsTHW+KuIuLiBkqj9EoKyeq6/MQYxHp6TkASKXUkVDxtc7Qek1CdCi8AGYU7cMX3rklQMsE3HzZbWuot0bAUSnujk/JXMl1zINID/uGPNSzb2jLDLX4uL0oLDQqrpbo=,iv:i+eIoD8Ls9dmy84byPYd+ChVr5vr6e1Fz++olukuqg8=,tag:bR4gYpCx8lbaaxO4fDfinQ==,type:str]
    version: 3.13.3
