apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Db/qJEYglIYP3ozF,iv:AZS+lpq/cxdezgdMwMR6aJ8XUoLl8ejq2YDknlhK+qg=,tag:eLnRzl2vYneUpIx8ziScNA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:PJIjXY0l0tsrTvPH,iv:K2mGWyW575Y9maBjDzR8z1AtNd5MYBgHCGPA/UribwQ=,tag:eErdgQnwMZsqHvv0Cb+Jjw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYUVqekc0YWd4dFcvcGMz
            Tm1BWUN6ckQvZ3VZaGxrWVBNalQxSG5mdW1RCnB6TFdFS0p3ZjhpWEt0c1REVHdJ
            YjVSejl0c1ZXWUIyT2hhVnJNbmtSOFkKLS0tIG1FZFlwbEgxS2djdUs5c0xvNkJG
            RUhnSTNRL2dSbWUwaHgvUEM3TFBVbGMK2wh3fOxOU2zO1Wgp4QZb18UeMpgh0fjw
            tuBDCtLB4M1uUnOlnufO3r6ka6nN82E0wbQ93j+BaXSyG8AqjWgE+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12plyrrm69vs9n5rjzlzqc6y33qrtgvpy0f5l847vswpqjaztzcgq22w8jq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T06:14:59Z"
    mac: ENC[AES256_GCM,data:Al2CWZMqANPSXWHevRxNjjYsj7APsycIlchukAer4i9N3Bmq3SnWfEZ0YR/nAE80xf3KH4shmwYn9cV8cQf4yeajuCUUlgRg1wxyFup9EFzSF2xdaDb/xhQxpkz99eoga+1ECvaoNf2Py6uW3kPsXdwKfjTlTMka4a7lcLZcu+E=,iv:1Iabux2+PaTE935grJhiFrPXy3IDKeQVHd2WLhnhexM=,tag:iozs9wbT2FFjjeX4NuKSKA==,type:str]
    version: 3.13.3
