apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:wOBCqbzRnODW1dj8,iv:540cCuXZN3wJUZ/kT6y4eaO2XDOosXFKKFdkv1PE3vM=,tag:kjgKJtZuSWuOM2WX1RAUNQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:bqm3H9pRuWowyvZ/,iv:DWyi/lZOXeleVLNUszhQR7Vx29MVzVKq8YgVRqTesvM=,tag:m2Gxk8m0OVPF9thssdlIqg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2lLajNkVkppSSt6bXpi
            VU4zenhPVGxqbmdob2dmWVoxem9oSXJ0eENNCmc4WDhxZXl1S1BLRTJCQk1wa1d3
            NWtHM1RJeS9SQkFFdHFoTHExdUk4bk0KLS0tIC9ITng0R2l4MHlNUlhJSVlTdWJC
            T3FFd1BMWW9JaFpDRkdpSEZ5WVBzZGMKm1vFIwmxfq7XFh2MLtVCql0YuVX+AAL8
            hO2Vf/McAu/ObbxCWd+sc9i60YiKhjkQOQAiOwj5dZ5s8e+/Qcv07Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12plyrrm69vs9n5rjzlzqc6y33qrtgvpy0f5l847vswpqjaztzcgq22w8jq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T06:02:23Z"
    mac: ENC[AES256_GCM,data:soWjCb+cTinYQ53oqctR5kwOEHAeKWCYnfvLGd5fi9Y1HfT2jyxrThIiObds2+KytS3HOqmwOTDcNWHkNRao2ngjOVys6U8EPekrAjU3IEcdfsVD4OZuUk8Ov5del81K3CwSvUqUHu+Dlye6YJePqqXHRKbuBKBggaeuGMU5yuE=,iv:2O473MzywZvWfujmtdIX8B4sj148sGwmLxbkNVaObOw=,tag:r59rJtUhmb3iISXkrNB8yg==,type:str]
    version: 3.13.3
