apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FQX+4l9av+eozfCd,iv:qeajt/vGRSYPaJrxzubxL6+BpepnNgxxce8ZP9/lZZQ=,tag:VD6s9wJ8H2u5MxyQNGs/JA==,type:str]
    user: ENC[AES256_GCM,data:mdp/zJZfhxs=,iv:zS7SuImi0elD4bjqJgeS9lsmoPJ+o1hlrS8KC7c++DA=,tag:vOLhHeYpbqfTZxqhn4qSVg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN21GWU1iZGdkRDB1MW5k
            MWx4eWd6cWh3MlJFa3VOMEFyd3BJbjRyMkZzCjl3SkZiZ3lua2huWUFxbUNFZkw0
            WTI2UnVxbmhCQlp4cmtMMDcxV0Y1WkEKLS0tIG9PYjdhdDg5WnQycE1ENEtJbFRY
            RXRzeXNTUkZvT3RXY01tZU9TNGx6RzQKFuyUFWHc+E/Aq1kGhneCX3EfOvahoGUO
            5G5T5tRdeAMLa4Mnpv3XAR/mcxzVUnyp3e4vaqF5UToIdzwljv62qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12plyrrm69vs9n5rjzlzqc6y33qrtgvpy0f5l847vswpqjaztzcgq22w8jq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T03:39:06Z"
    mac: ENC[AES256_GCM,data:J/GVwoGgkmIamKJ/gk3mEISBZlhW6m1LjVAaS1kuBDkQU50eZVzTUOrhemNOC0NJ8hA/563r/+8lKu6tD+Dc+aTsoZSVr5ixJ4ld20gXuNzgTKCsQJ9omOS5u7Vensl+eYEkFJVg7HYHRqgGNXZEFGf/miEGO2kgROFMp6CVhGM=,iv:hxdIHvUFWS0ybkO68kSC8bmjEP7sTIbJgPDEd7h47co=,tag:YhrooooKrnijyzuvhN3rng==,type:str]
    version: 3.13.3
