apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Hobx7Z+mgS+iDORvlOt8cGPFgSmoaeUyYNKcybp2tWR9GUAso14wOYn1EY6V7Zy17AypW9k9cdY=,iv:wjqFpgOMcj69P8CRFDEsjvJkhck8rqsmG8II0UoHIzs=,tag:uIhx9kKCnD7d2T4sF5a8qg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS05HZmVYTDhaS3doeVlS
            ZkhaOTk2QXdCSzBTSkszbzhqRzZ4NnpydkNnCjNyZFdGY0NoU3pONVgxQ0ViSTlV
            UU8wNEFIVnZRZnNxaSsxcXo1K2lza0EKLS0tIDRkalZLR3RuUDBSRWJyQW1nYU56
            RzdrbERDaEM2VU41ZEtwekRHd2lYWGsKDwg5KqzAyK1jf+Pt0eANFM4k/eEoqIFm
            Y5jeXZqprZWMNGHgqWGBBpK7jvBhmkRD4xcZ69DL4zg+iEoBs/+BnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12plyrrm69vs9n5rjzlzqc6y33qrtgvpy0f5l847vswpqjaztzcgq22w8jq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T15:20:54Z"
    mac: ENC[AES256_GCM,data:ssrfdn8R71dWjj4DwgfTMjI1Cf4eBnbgEqn7LJW9qI6ifxI14c2QWDnBk2JymZRLsaeNKWegB4r6emJWUVJNPbMwWJLPkJeFLwizXyy2MiiAkgC47dF5TYtWAhvY8h8Q7eYUu68nszM83G7tvtquL5B0gczg3RQPIPCIFNQLFI8=,iv:On2QxkbZIfo99cohBgI1Y4crty83d6aq4Q1U/z7NF7Y=,tag:ErH7qTqDsDnv7Q2Vj9fPuw==,type:str]
    version: 3.13.3
